title: DESA
email: elitsa0897@gmail.com
description: Second-hamd clothes
destination: docs
baseurl: "/CSS-Advanced-Project-Assignment"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: Elitsa Dimitrova
github_username:  Elitsa-Dimitrova
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js